In [20]:
import numpy as np

In [37]:
a=np.array([1,2,3,4,5,6,7,8,9,10])

In [22]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
type(a)

numpy.ndarray

In [24]:
print(a.ndim)

1


In [25]:
a.shape

(10,)

In [26]:
len(a)

10

In [27]:
a.itemsize

4

In [31]:
a.dtype

dtype('float64')

In [32]:
a[-1]

10.0

In [33]:
a[ : ]

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.])

In [34]:
a[0:1]

array([ 1.])

In [35]:
a[0:3]

array([ 1.,  2.,  3.])

In [39]:
a[-1:-3]

array([], dtype=int32)

In [40]:
a[-1: ]

array([10])

In [41]:
a[ :-1]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
a[-1:-4]

array([], dtype=int32)

In [43]:
a[: : 1]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
a[: : 2]

array([1, 3, 5, 7, 9])

In [45]:
a[1::2]

array([ 2,  4,  6,  8, 10])

In [46]:
a[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [47]:
a[::-2]

array([10,  8,  6,  4,  2])